### ISSUE TITLE
Instructions on how to configure this to work with Aria Operations SaaS?

### ISSUE THREAD

**Issue by jHumeLPL** [prydin/aria-operations-plug-in-for-grafana#21]
Man, this looks like _exactly_ what I need.  I've installed it fine into my Grafana instance, but when going to add it as a datasource it only allows you to put in a hostname/IP for an Aria Operations host and a username/password for authentication.  We use Aria Operations for VMWare Cloud Services (so Aria Operations SaaS).  The authentication method for that is to use a "refresh_token" that then generates a temporary access_token.  Not a username and password.

**Is this plugin currently not compatible with SaaS based Aria?  If not, are there plans to add that functionality in soon?** 
 Because, wow do I love this plugin's features.  The Aria API is quite complex and trying to make it work with the Infinity plugin is a real pain...

Thanks for your help and seriously, even if it's currently not compatible with SaaS, really, _really_ great work!

**Comment by jHumeLPL** [comment]
Upon further investigation, it appears that yes, this _won't_ currently work with the SaaS based version of Aria Operations... Which is defintely a bummer because, as I said above, this looks amazing.  

I don't think it would take a lot to make it compatible though.  Just updating the plugin datasource config page to allow choosing between username/password auth for local instances of Aria and CSP Token auth for SaaS based instances.  Other than that, all of the functions of the plugin itself should work fine.

**Comment by prydin** [comment]
I'm working on this right now. Stay tuned!

**Comment by prydin** [comment]
Just released 1.1.0 which supports SaaS. Closing ticket.

**Comment by jHumeLPL** [comment]
> Just released 1.1.0 which supports SaaS. Closing ticket.

Really great news!  Can't wait to try this out.  Thanks so much!
