### ISSUE TITLE
module.js not found

### ISSUE THREAD

**Issue by MohsenSedaghat** [prydin/aria-operations-plug-in-for-grafana#4]
Hi, I tried to inuse this plugin
I got this error when I wanted to set data source
Fetch error: 404 Not Found Instantiating /public/plugins/vmware-ariaoperations-datasource/module.js

**Comment by prydin** [comment]
Could you please describe how you installed the plugin?

**Comment by AnushthaK** [comment]
I am also facing the same issue. Getting Fetch error: 404 Not Found Instantiating /public/plugins/vmware-ariaoperations-datasource/module.js after adding datasource.
Grafana version: 9.4.7
Steps followed for installation:
1) Clone the project by using the command git clone <url>
2) make a zip of the cloned project and transferred to the server.
3) unzipped the file in plugins directory for grafana
4) changed ownership of plugin to grafana:grafana
5) added below line in grafan.ini file:
[plugins] 
allow_loading_unsigned_plugins=vmware-ariaoperations-datasource
6) restarted grafana-server
7) Logged in to grafana and added datasource (I was getting aria operation datasource in options)
8)  Getting the mentioned error: Fetch error: 404 Not Found Instantiating /public/plugins/vmware-ariaoperations-datasource/module.js
9) 
![image](https://github.com/prydin/aria-operations-plug-in-for-grafana/assets/127762403/66bc66d1-f145-403b-95f9-565e76ae3446)

**Comment by baptistepas** [comment]
Hi, i have the same issue :

Fetch error: 404 Not Found Instantiating https://.../plugins/vmware-ariaoperations-datasource/module.js Loading plugins/vmware-ariaoperations-datasource/module

I followed step but still this error .

I have a module in .ts on src/module.ts but any module.js.

version "aria-operations-plug-in-for-grafana-1.0.0" for the compatibility with my grafana > 9.2

thx for your help

**Comment by prydin** [comment]
I've seen this happening occasionally. Looking into it!

**Comment by kamulchik** [comment]
Have the same issue. [v9.4.3] Rocky 9.1

**Comment by prydin** [comment]
Did you follow the installation instructions? Every time I've seen someone run into this, it's been because the correct files weren't in the correct directory. It might be a good idea so check that you have a sub-directory in you plugin directory with module.js in it.

**Comment by kamulchik** [comment]
> Did you follow the installation instructions? Every time I've seen someone run into this, it's been because the correct files weren't in the correct directory. It might be a good idea so check that you have a sub-directory in you plugin directory with module.js in it.

I added allow_loading_unsigned_plugins=vmware-ariaoperations-datasource to grafana.ini at section [plugins]
unzip aria-operations-plug-in-for-grafana-main.zip
mv aria-operations-plug-in-for-grafana-main /var/lib/grafana/plugins/
and restart grafana-server.
In my config, plugin directory path:  /var/lib/grafana/plugins
![image](https://github.com/prydin/aria-operations-plug-in-for-grafana/assets/13658089/556ca91d-692b-4d64-b08a-f69dc1617ba8)

**Comment by prydin** [comment]
Please read the installation instructions. You need to download the release zip file and unzip it.

**Comment by kamulchik** [comment]
Really so sorry. It''s work fine.

**Comment by prydin** [comment]
Actually, I'm reading the instructions now and they're not very clear. I'll fix that!
