### ISSUE TITLE
No data in queries

### ISSUE THREAD

**Issue by Four24** [prydin/aria-operations-plug-in-for-grafana#45]
I've been playing with it for a few days but I am not able to visualize any metrics because no data is being returned.
Below is what I get when using the plugin

![AriaOpsError](https://github.com/prydin/aria-operations-plug-in-for-grafana/assets/150865526/6fc2d011-372b-4934-bd22-297aa5c2717c)

**Comment by prydin** [comment]
Make sure that there's data available for that metric. Some of the capacity metrics aren't populated by default. You can try with something you know will be there, such as `cpu|demandmhz`.

**Comment by Four24** [comment]
Okay that works. Is it possible to pull the metrics for all the virtual machines in a folder using conditional query?

e.g. all the vCPU provisioned for a folder with test systems

**Comment by prydin** [comment]
Yes, you can filter on the `parentFolder` property. Like this:
```
resource(VMWARE:VirtualMachine).whereProperties(summary|parentFolder = "test").metrics(cpu|demandmhz)
```

**Comment by prydin** [comment]
Closing this since the actual issue is resolved.

**Comment by Four24** [comment]
One last question. Is it possible to get a list of datastores a virtual machine is using and how much space it is using?

eg. TestVM1 is using 2 datastores. VM is using 60 GB on datastore1 and 105GB on datastore 2.
