### ISSUE TITLE
Problem with Multi-value Selection options with Variables

### ISSUE THREAD

**Issue by ngl95lam** [prydin/aria-operations-plug-in-for-grafana#56]
Hi, I got a problem with Multi-value.
I got No data with Multi-value, If I set single variable, Data will show up.
![image](https://github.com/user-attachments/assets/09be3ecc-a672-4b15-8b33-0428d60c446a)

Please help.
![image](https://github.com/user-attachments/assets/a3117839-c2a6-4ba8-8064-80e3a9e91b20)
![image](https://github.com/user-attachments/assets/b09b8982-4882-48e0-8a27-e7825b1ec0a0)

**Comment by ngl95lam** [comment]
This is single querry:
`Object
traceId:undefined
request:Object
method:"POST"
url:"api/datasources/proxy/uid/d7e1ac02-44d9-46cc-ad75-83a9686aa465/aria-operations/suite-api/api/resources/stats/query"
data:Object
resourceId:Array[1]
statKey:Array[1]
begin:"1721020252820"
end:"1721041852820"
rollUpType:"AVG"
intervalType:"MINUTES"
intervalQuantifier:"5"
responseType:"text"
hideFromInspector:false
response:"{\"values\":[{\"resourceId\":\"fdeab5ae-f76b-4347-a507-48f61439c8d2\",\"stat-list\":{\"stat\":[{\"timestamps\":[1721020499999,1721020799999,1721021099999,1721021399999,1721021699999,1721021999999,1721022299999,1721022599999,1721022899999,1721023199999,1721023499999,1721023799999,1721024099999,1721024399999,1721024699999,1721024999999,1721025299999,1721025599999,1721025899999,1721026199999,1721026499999,1721026799999,1721027099999,1721027399999,1721027699999,1721027999999,1721028299999,1721028599999,1721028899999,1721029199999,1721029499999,1721029799999,1721030099999,1721030399999,1721030699999,1721030999999,1721031299999,1721031599999,1721031899999,1721032199999,1721032499999,1721032799999,1721033099999,1721033399999,1721033699999,1721033999999,1721034299999,1721034599999,1721034899999,1721035199999,1721035499999,1721035799999,1721036099999,1721036399999,1721036699999,1721036999999,1721037299999,1721037599999,1721037899999,1721038199999,1721038499999,1721038799999,1721039099999,1721039399999,1721039699999,1721039999999,1721040299999,1721040599999,1721040899999,1721041199999,1721041499999,1721041799999],\"statKey\":{\"key\":\"virtualDisk:Aggregate of all instances|totalLatency\"},\"rollUpType\":\"AVG\",\"intervalUnit\":{\"quantifier\":5,\"intervalType\":\"MINUTES\"},\"data\":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.13333334028720856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2666666805744171,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]}]}}]}"`

Error with multiple-variables:
`Object
traceId:undefined
request:Object
method:"POST"
url:"api/datasources/proxy/uid/d7e1ac02-44d9-46cc-ad75-83a9686aa465/aria-operations/suite-api/api/resources/query?pageSize=1000"
data:Object
adapterKind:Array[1]
regex:Array[0]
name:Array[1]
resourceId:Array[0]
resourceKind:Array[1]
resourceState:Array[0]
resourceHealth:Array[0]
resourceStatus:Array[0]
responseType:"text"
hideFromInspector:false
response:"{\"pageInfo\":{\"totalCount\":0,\"page\":0,\"pageSize\":1000},\"links\":[{\"href\":\"/suite-api/api/resources/query?page=0&amp;pageSize=1000\",\"rel\":\"SELF\",\"name\":\"current\"},{\"href\":\"/suite-api/api/resources/query?page=0&amp;pageSize=1000\",\"rel\":\"RELATED\",\"name\":\"first\"},{\"href\":\"/suite-api/api/resources/query?page=0&amp;pageSize=1000\",\"rel\":\"RELATED\",\"name\":\"last\"}],\"resourceList\":[]}"`

**Comment by prydin** [comment]
Multi selection is not yet supported.

**Comment by ngl95lam** [comment]
I hope you can have a new update soon.
Thanh you,.

> Multi selection is not yet supported.
