### ISSUE TITLE
[Bug] Super Metric does not work in Advanced mode

### ISSUE THREAD

**Issue by ngl95lam** [prydin/aria-operations-plug-in-for-grafana#57]
Hi,
With normal mode, super metric work like a charm. But if I change to Advanced Mode, Grafana shows error with White Space.
![image](https://github.com/user-attachments/assets/e1c05fde-7de7-44dd-a4c7-9f1045c44352)

Error in Advanced mode:
![image](https://github.com/user-attachments/assets/9ae54b4c-8390-4944-ac05-9c5d71233bbd)

![image](https://github.com/user-attachments/assets/f6a59d1d-ed09-42b6-9d63-95774122c637)

Does anyone have any idea how to fix this?
Thank you.

**Comment by prydin** [comment]
It's because of the space in the metric name. You can use backtick to quote it:

```resource(SometResource).all().metrics(`Super Metric|yadayada`)```

You need version 1.2.0 for this to work.
